# Generated by Django 5.1.6 on 2025-04-05 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('funding', 'Достижение цели по финансированию'), ('users', 'Достижение по количеству пользователей'), ('revenue', 'Достижение по выручке'), ('milestone', 'Достижение вехи проекта'), ('rating', 'Высокий рейтинг'), ('verification', 'Верификация'), ('custom', 'Пользовательское достижение')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=50)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='startups.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('investor_views', models.IntegerField(default=0)),
                ('contact_requests', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('investments_count', models.IntegerField(default=0)),
                ('successful_startups', models.IntegerField(default=0)),
                ('achievements_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запись таблицы лидеров',
                'verbose_name_plural': 'Таблица лидеров',
                'ordering': ['-points'],
            },
        ),
        migrations.CreateModel(
            name='StartupMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customers', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('churn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='startups.startup')),
            ],
            options={
                'verbose_name': 'Метрики стартапа',
                'verbose_name_plural': 'Метрики стартапов',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Вход в систему'), ('startup_view', 'Просмотр стартапа'), ('investment', 'Инвестиция'), ('comment', 'Комментарий'), ('rating', 'Оценка'), ('message', 'Сообщение'), ('document', 'Работа с документами')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Активность пользователя',
                'verbose_name_plural': 'Активность пользователей',
                'ordering': ['-timestamp'],
            },
        ),
    ]
